name: ConvergioApp
options:
  bundleIdPrefix: com.convergio
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.2"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""
    ENABLE_HARDENED_RUNTIME: YES
    PRODUCT_NAME: Convergio
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  ConvergioCore:
    path: ../ConvergioCore

targets:
  ConvergioApp:
    type: application
    platform: macOS
    sources:
      - path: ConvergioApp
        excludes:
          - "**/*.xcassets"
      - path: ConvergioApp/Resources
        type: folder
        buildPhase: resources
        optional: true
    settings:
      base:
        INFOPLIST_FILE: ConvergioApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.convergio.app
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/../build/lib"
        OTHER_LDFLAGS:
          - "-lconvergio"
          - "-lcurl"
          - "-lreadline"
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/../include"
          - "$(PROJECT_DIR)/../ConvergioCore/Sources/CConvergio"
        SWIFT_INCLUDE_PATHS:
          - "$(PROJECT_DIR)/../ConvergioCore/Sources/CConvergio"
        ENABLE_APP_SANDBOX: YES
        APP_SANDBOX_NETWORK_CLIENT: YES
        APP_SANDBOX_NETWORK_SERVER: NO
        APP_SANDBOX_FILE_ACCESS_USER_SELECTED: YES
    dependencies:
      - package: ConvergioCore
    entitlements:
      path: ConvergioApp/ConvergioApp.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.network.client: true
        com.apple.security.files.user-selected.read-write: true
    preBuildScripts:
      - name: Build Static Library
        script: |
          # Build libconvergio.a if not present
          if [ ! -f "${PROJECT_DIR}/../build/lib/libconvergio.a" ]; then
            echo "Building libconvergio.a..."
            cd "${PROJECT_DIR}/.."
            mkdir -p build && cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release
            make convergio_lib -j8
          fi
        basedOnDependencyAnalysis: false

  ConvergioAppTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ConvergioAppTests
    settings:
      base:
        INFOPLIST_FILE: ConvergioAppTests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.convergio.app.tests
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Convergio.app/Contents/MacOS/Convergio"
        BUNDLE_LOADER: "$(TEST_HOST)"
    dependencies:
      - target: ConvergioApp
      - package: ConvergioCore

  ConvergioAppUITests:
    type: bundle.ui-testing
    platform: macOS
    sources:
      - path: ConvergioAppUITests
    settings:
      base:
        INFOPLIST_FILE: ConvergioAppUITests/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.convergio.app.uitests
        TEST_TARGET_NAME: ConvergioApp
    dependencies:
      - target: ConvergioApp

schemes:
  ConvergioApp:
    build:
      targets:
        ConvergioApp: all
        ConvergioAppTests: [test]
        ConvergioAppUITests: [test]
    run:
      config: Debug
      commandLineArguments:
        "--uitesting": false
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: ConvergioAppTests
          parallelizable: true
          randomExecutionOrder: true
        - name: ConvergioAppUITests
          parallelizable: false
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
