//! Config rendering for `cvg setup`.

use crate::cli_setup_inference;

pub(crate) fn render_full_config(
    node_name: &str,
    role: &str,
    use_tailscale: bool,
    inference: &cli_setup_inference::InferenceChoice,
    telegram_enabled: bool,
) -> String {
    let transport = if use_tailscale { "tailscale" } else { "lan" };
    let discovery = if use_tailscale { "tailscale" } else { "mdns" };
    let model = if inference.use_mlx {
        "qwen-7b-coder"
    } else {
        "none"
    };
    let model_path = inference.mlx_model.as_deref().unwrap_or("");

    format!(
        r#"# Convergio Platform Configuration
# Generated by `cvg setup`

[node]
name = "{node_name}"
role = "{role}"

[daemon]
port = 8420
auto_update = true

[mesh]
transport = "{transport}"
discovery = "{discovery}"

[mesh.tailscale]
enabled = {use_tailscale}

[inference]
default_model = "claude-sonnet-4-6"
api_key_env = "ANTHROPIC_API_KEY"

[kernel]
model = "{model}"
model_path = "{model_path}"
max_tokens = 2048

[telegram]
enabled = {telegram_enabled}
"#
    )
}
