// Auto-generated file - do not edit manually
// Generated by scripts/embed_agents.sh

#ifndef EMBEDDED_AGENTS_H
#define EMBEDDED_AGENTS_H

#include <stddef.h>

typedef struct {
    const char* filename;
    const char* content;
    size_t length;
} EmbeddedAgent;

extern const EmbeddedAgent EMBEDDED_AGENTS[];
extern const size_t EMBEDDED_AGENTS_COUNT;

// Get embedded agent by filename (without path)
const EmbeddedAgent* get_embedded_agent(const char* filename);

// Get all embedded agents
const EmbeddedAgent* get_all_embedded_agents(size_t* count);

#endif // EMBEDDED_AGENTS_H
