/**
 * CONVERGIO EDUCATION - HTML INTERACTIVE WRAPPER
 *
 * Simple wrapper for saving and opening LLM-generated HTML pages.
 * The actual HTML content is generated by the maestri via their LLM prompts.
 *
 * Philosophy: The maestri have the pedagogical intelligence to create
 * custom visualizations. They generate HTML/CSS/JS via LLM and use
 * this wrapper to save and present it to the student.
 *
 * Example workflow:
 * 1. Euclide decides student needs a visual explanation
 * 2. Euclide asks LLM: "Create interactive HTML for Pythagorean theorem..."
 * 3. LLM returns HTML string
 * 4. Euclide calls html_save_and_open(html, "teorema_pitagora")
 * 5. Browser opens with the visualization
 *
 * Copyright (c) 2025 Convergio.io
 * Licensed under MIT License
 */

#include "nous/education.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/stat.h>
#include <errno.h>

// ============================================================================
// CONSTANTS
// ============================================================================

// User-friendly location for education content
#define HTML_LESSONS_DIR "/Documents/ConvergioEducation"

// ============================================================================
// HELPERS
// ============================================================================

static char* get_lessons_dir(void) {
    const char* home = getenv("HOME");
    if (!home) return NULL;

    size_t len = strlen(home) + strlen(HTML_LESSONS_DIR) + 1;
    char* path = malloc(len);
    if (path) {
        snprintf(path, len, "%s%s", home, HTML_LESSONS_DIR);
    }
    return path;
}

static int ensure_lessons_dir(void) {
    const char* home = getenv("HOME");
    if (!home) return -1;

    // Create ~/Documents/ConvergioEducation - user-friendly location
    char* dir = get_lessons_dir();
    if (!dir) return -1;

    int result = mkdir(dir, 0755);
    free(dir);

    return (result == 0 || errno == EEXIST) ? 0 : -1;
}

static char* sanitize_filename(const char* topic) {
    if (!topic) return strdup("lesson");

    size_t len = strlen(topic);
    if (len > 60) len = 60;

    char* safe = malloc(len + 1);
    if (!safe) return strdup("lesson");

    size_t j = 0;
    for (size_t i = 0; i < len && topic[i]; i++) {
        char c = topic[i];
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
            (c >= '0' && c <= '9') || c == '-' || c == '_') {
            safe[j++] = c;
        } else if (c == ' ') {
            safe[j++] = '_';
        }
    }
    safe[j] = '\0';

    if (j == 0) {
        free(safe);
        return strdup("lesson");
    }

    return safe;
}

// ============================================================================
// PUBLIC API
// ============================================================================

/**
 * Save HTML content to a file and return the path.
 * The HTML is typically generated by an LLM based on the maestro's prompt.
 *
 * @param html_content Complete HTML document string
 * @param topic Topic name for filename
 * @return Path to saved file (caller must free), or NULL on error
 */
char* html_save(const char* html_content, const char* topic) {
    if (!html_content) return NULL;

    // Ensure directory exists
    if (ensure_lessons_dir() != 0) {
        fprintf(stderr, "[html] Failed to create lessons directory\n");
        return NULL;
    }

    // Generate filename with timestamp
    char* safe_topic = sanitize_filename(topic);
    char* dir = get_lessons_dir();
    if (!dir) {
        free(safe_topic);
        return NULL;
    }

    time_t now = time(NULL);
    struct tm* tm_info = localtime(&now);
    char timestamp[16];
    strftime(timestamp, sizeof(timestamp), "%Y%m%d_%H%M%S", tm_info);

    size_t path_len = strlen(dir) + strlen(safe_topic) + strlen(timestamp) + 16;
    char* filepath = malloc(path_len);
    if (!filepath) {
        free(safe_topic);
        free(dir);
        return NULL;
    }
    snprintf(filepath, path_len, "%s/%s_%s.html", dir, safe_topic, timestamp);

    free(safe_topic);
    free(dir);

    // Write file
    FILE* f = fopen(filepath, "w");
    if (!f) {
        fprintf(stderr, "[html] Failed to create file: %s\n", filepath);
        free(filepath);
        return NULL;
    }

    fprintf(f, "%s", html_content);
    fclose(f);

    fprintf(stderr, "[html] Saved: %s\n", filepath);
    return filepath;
}

/**
 * Open HTML file in the default browser (macOS only).
 *
 * @param filepath Path to HTML file
 * @return 0 on success, -1 on error
 */
int html_open_in_browser(const char* filepath) {
    if (!filepath) return -1;

#ifdef __APPLE__
    char cmd[1024];
    snprintf(cmd, sizeof(cmd), "open \"%s\"", filepath);
    int result = system(cmd);
    return (result == 0) ? 0 : -1;
#else
    fprintf(stderr, "[html] Browser open only supported on macOS\n");
    return -1;
#endif
}

/**
 * Save HTML and open in browser (convenience function).
 *
 * @param html_content Complete HTML document string
 * @param topic Topic name for filename
 * @return Path to saved file (caller must free), or NULL on error
 */
char* html_save_and_open(const char* html_content, const char* topic) {
    char* path = html_save(html_content, topic);
    if (path) {
        html_open_in_browser(path);
    }
    return path;
}

// ============================================================================
// LEGACY API (for backwards compatibility with template-based approach)
// ============================================================================

// These functions wrap a minimal template around content.
// Prefer using html_save() with full LLM-generated HTML.

static const char* BASE_TEMPLATE =
    "<!DOCTYPE html>\n"
    "<html lang=\"it\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "  <title>%s - Convergio Education</title>\n"
    "  <style>\n"
    "    * { margin: 0; padding: 0; box-sizing: border-box; }\n"
    "    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
    "           background: linear-gradient(135deg, #667eea 0%%, #764ba2 100%%);\n"
    "           min-height: 100vh; padding: 2rem; }\n"
    "    .container { max-width: 900px; margin: 0 auto; }\n"
    "    .card { background: white; border-radius: 1rem; padding: 2rem; margin: 1rem 0;\n"
    "            box-shadow: 0 20px 25px -5px rgb(0 0 0 / 0.1); }\n"
    "    h1 { color: #1a202c; font-size: 2rem; margin-bottom: 1rem; }\n"
    "    p { color: #718096; line-height: 1.8; }\n"
    "    .footer { text-align: center; color: rgba(255,255,255,0.8); padding: 2rem; }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <div class=\"container\">\n"
    "    <div class=\"card\">\n"
    "      <h1>%s</h1>\n"
    "      %s\n"
    "    </div>\n"
    "  </div>\n"
    "  <div class=\"footer\">Generato con ❤️ da Convergio Education</div>\n"
    "</body>\n"
    "</html>\n";

char* html_generate(const char* topic, HtmlContentType type) {
    (void)type;  // Type is a hint, but we use generic template

    if (!topic) return NULL;

    size_t len = strlen(BASE_TEMPLATE) + strlen(topic) * 2 + 256;
    char* html = malloc(len);
    if (!html) return NULL;

    snprintf(html, len, BASE_TEMPLATE, topic, topic, "<p>Contenuto in elaborazione...</p>");
    return html;
}

char* html_generate_and_open(const char* topic, HtmlContentType type) {
    char* html = html_generate(topic, type);
    if (!html) return NULL;

    char* path = html_save_and_open(html, topic);
    free(html);
    return path;
}

char* html_generate_geometry(const char* topic) {
    return html_generate(topic, HTML_CONTENT_GEOMETRY);
}

char* html_generate_physics(const char* topic) {
    return html_generate(topic, HTML_CONTENT_PHYSICS);
}

char* html_generate_timeline(const char* topic) {
    return html_generate(topic, HTML_CONTENT_TIMELINE);
}

char* html_generate_lesson(const char* topic, const char* content_html) {
    if (!topic) return NULL;

    size_t len = strlen(BASE_TEMPLATE) + strlen(topic) * 2 +
                 (content_html ? strlen(content_html) : 50) + 256;
    char* html = malloc(len);
    if (!html) return NULL;

    snprintf(html, len, BASE_TEMPLATE, topic, topic,
             content_html ? content_html : "<p>Contenuto in elaborazione...</p>");
    return html;
}

// ============================================================================
// TL10: LLM PROMPT TEMPLATES FOR COMMON VISUALS
// ============================================================================

/**
 * Get LLM prompt template for generating geometry visualizations.
 * The LLM will generate interactive HTML with SVG/Canvas.
 */
const char* html_template_prompt_geometry(void) {
    return
        "Generate an interactive HTML visualization for geometry.\n"
        "REQUIREMENTS:\n"
        "- Use SVG for precise geometric shapes (triangles, circles, angles)\n"
        "- Include labels for all measurements and angles\n"
        "- Add CSS animations to highlight key relationships\n"
        "- Make it responsive (max-width: 800px)\n"
        "- Use color coding: blue for given values, red for unknown\n"
        "- Include step-by-step visual proof if applicable\n"
        "- Add Italian labels (angolo, lato, diagonale, etc.)\n"
        "STYLE: Modern, clean, professional with gradient backgrounds.\n"
        "OUTPUT: Complete standalone HTML document.";
}

/**
 * Get LLM prompt template for generating historical timelines.
 */
const char* html_template_prompt_timeline(void) {
    return
        "Generate an interactive HTML timeline visualization.\n"
        "REQUIREMENTS:\n"
        "- Horizontal scrollable timeline with event cards\n"
        "- Each event: date, title, short description, optional image placeholder\n"
        "- Color-code by category (wars=red, discoveries=green, culture=purple)\n"
        "- Hover effects to expand event details\n"
        "- Responsive design with mobile-friendly vertical fallback\n"
        "- Include zoom controls (+/-) for different time scales\n"
        "STYLE: Classic parchment aesthetic with modern interactions.\n"
        "OUTPUT: Complete standalone HTML document.";
}

/**
 * Get LLM prompt template for generating physics diagrams.
 */
const char* html_template_prompt_physics(void) {
    return
        "Generate an interactive HTML physics diagram.\n"
        "REQUIREMENTS:\n"
        "- Use Canvas or SVG for dynamic visualizations\n"
        "- Show force vectors with arrows (labeled with magnitude)\n"
        "- Include interactive sliders to adjust parameters\n"
        "- Real-time calculation updates when values change\n"
        "- Unit labels (N, m/s², kg, etc.)\n"
        "- Include the relevant formula displayed prominently\n"
        "STYLE: Scientific, clean, with grid background.\n"
        "OUTPUT: Complete standalone HTML document with JavaScript.";
}

/**
 * Get LLM prompt template for generating biology diagrams.
 */
const char* html_template_prompt_biology(void) {
    return
        "Generate an interactive HTML biology diagram.\n"
        "REQUIREMENTS:\n"
        "- Detailed labeled diagram (cell, organ, organism)\n"
        "- Click/hover on parts to see descriptions\n"
        "- Use SVG for scalable illustrations\n"
        "- Color-code different structures/systems\n"
        "- Include a legend explaining colors/symbols\n"
        "- Add zoom capability for detailed views\n"
        "STYLE: Scientific illustration style, pastel colors.\n"
        "OUTPUT: Complete standalone HTML document.";
}

/**
 * Get LLM prompt template for generating math function graphs.
 */
const char* html_template_prompt_math_graph(void) {
    return
        "Generate an interactive HTML math graph visualization.\n"
        "REQUIREMENTS:\n"
        "- Use Canvas for plotting functions\n"
        "- Coordinate grid with labeled axes\n"
        "- Interactive: drag to pan, scroll to zoom\n"
        "- Plot the function with smooth curve\n"
        "- Highlight key points (zeros, maxima, minima, asymptotes)\n"
        "- Display equation prominently with LaTeX-style formatting\n"
        "- Add sliders to modify function parameters if applicable\n"
        "STYLE: Clean mathematical plotting, dark grid on light background.\n"
        "OUTPUT: Complete standalone HTML document with JavaScript.";
}

/**
 * Get LLM prompt template for generating interactive quizzes.
 */
const char* html_template_prompt_quiz(void) {
    return
        "Generate an interactive HTML quiz.\n"
        "REQUIREMENTS:\n"
        "- Multiple choice questions with 4 options each\n"
        "- Immediate feedback on selection (green=correct, red=wrong)\n"
        "- Explanation shown after each answer\n"
        "- Progress bar showing questions completed\n"
        "- Final score with encouraging message\n"
        "- Option to retry incorrect questions\n"
        "- Confetti animation on perfect score\n"
        "STYLE: Gamified, colorful, encouraging.\n"
        "OUTPUT: Complete standalone HTML document with JavaScript.";
}

/**
 * Get LLM prompt template for generating flashcards.
 */
const char* html_template_prompt_flashcards(void) {
    return
        "Generate interactive HTML flashcards.\n"
        "REQUIREMENTS:\n"
        "- Click to flip between question and answer\n"
        "- Smooth 3D flip animation\n"
        "- Navigation arrows for next/previous card\n"
        "- Shuffle button\n"
        "- Progress indicator (card X of Y)\n"
        "- Mark cards as 'known' or 'review' for spaced repetition\n"
        "- Keyboard navigation (arrows, space to flip)\n"
        "STYLE: Clean cards with subtle shadows, colorful accents.\n"
        "OUTPUT: Complete standalone HTML document with JavaScript.";
}

/**
 * Get appropriate prompt template based on content type.
 */
const char* html_get_template_prompt(HtmlContentType type) {
    switch (type) {
        case HTML_CONTENT_GEOMETRY: return html_template_prompt_geometry();
        case HTML_CONTENT_TIMELINE: return html_template_prompt_timeline();
        case HTML_CONTENT_PHYSICS:  return html_template_prompt_physics();
        case HTML_CONTENT_BIOLOGY:  return html_template_prompt_biology();
        case HTML_CONTENT_GRAPH:    return html_template_prompt_math_graph();
        case HTML_CONTENT_QUIZ:     return html_template_prompt_quiz();
        case HTML_CONTENT_FLASHCARD: return html_template_prompt_flashcards();
        default:                    return NULL;
    }
}
