#!/bin/bash
# Generate embedded_agents.c from agent definition files
# This embeds all .md files as static strings in the binary

AGENTS_DIR="src/agents/definitions"
OUTPUT_FILE="src/agents/embedded_agents.c"
HEADER_FILE="include/nous/embedded_agents.h"

echo "Generating embedded agents from $AGENTS_DIR..."

# Generate header
cat > "$HEADER_FILE" << 'EOF'
// Auto-generated file - do not edit manually
// Generated by scripts/embed_agents.sh

#ifndef EMBEDDED_AGENTS_H
#define EMBEDDED_AGENTS_H

#include <stddef.h>

typedef struct {
    const char* filename;
    const char* content;
    size_t length;
} EmbeddedAgent;

extern const EmbeddedAgent EMBEDDED_AGENTS[];
extern const size_t EMBEDDED_AGENTS_COUNT;

// Get embedded agent by filename (without path)
const EmbeddedAgent* get_embedded_agent(const char* filename);

// Get all embedded agents
const EmbeddedAgent* get_all_embedded_agents(size_t* count);

#endif // EMBEDDED_AGENTS_H
EOF

# Generate C file
cat > "$OUTPUT_FILE" << 'EOF'
// Auto-generated file - do not edit manually
// Generated by scripts/embed_agents.sh

#include "nous/embedded_agents.h"
#include <string.h>

EOF

# Process each .md file
count=0
for file in "$AGENTS_DIR"/*.md; do
    if [ -f "$file" ]; then
        filename=$(basename "$file")
        varname=$(echo "$filename" | sed 's/[^a-zA-Z0-9]/_/g' | sed 's/^/agent_/')

        echo "// $filename" >> "$OUTPUT_FILE"
        echo "static const char ${varname}[] =" >> "$OUTPUT_FILE"

        # Escape the content for C string
        while IFS= read -r line || [ -n "$line" ]; do
            # Escape backslashes, quotes, and convert to C string
            escaped=$(echo "$line" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g' | sed 's/	/\\t/g')
            echo "    \"$escaped\\n\"" >> "$OUTPUT_FILE"
        done < "$file"

        echo ";" >> "$OUTPUT_FILE"
        echo "" >> "$OUTPUT_FILE"

        ((count++))
    fi
done

# Generate the array
echo "const EmbeddedAgent EMBEDDED_AGENTS[] = {" >> "$OUTPUT_FILE"

for file in "$AGENTS_DIR"/*.md; do
    if [ -f "$file" ]; then
        filename=$(basename "$file")
        varname=$(echo "$filename" | sed 's/[^a-zA-Z0-9]/_/g' | sed 's/^/agent_/')
        echo "    {\"$filename\", $varname, sizeof($varname) - 1}," >> "$OUTPUT_FILE"
    fi
done

echo "};" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "const size_t EMBEDDED_AGENTS_COUNT = $count;" >> "$OUTPUT_FILE"

# Generate lookup functions
cat >> "$OUTPUT_FILE" << 'EOF'

const EmbeddedAgent* get_embedded_agent(const char* filename) {
    for (size_t i = 0; i < EMBEDDED_AGENTS_COUNT; i++) {
        if (strcmp(EMBEDDED_AGENTS[i].filename, filename) == 0) {
            return &EMBEDDED_AGENTS[i];
        }
    }
    return NULL;
}

const EmbeddedAgent* get_all_embedded_agents(size_t* count) {
    if (count) *count = EMBEDDED_AGENTS_COUNT;
    return EMBEDDED_AGENTS;
}
EOF

echo "Generated $count embedded agents in $OUTPUT_FILE"
